name: CD

on:
  push:
    branches: [ main ]
    paths:
    - '**.bicep'
  pull_request:
    branches: [ main ]
    paths:
    - '**.bicep'
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *" #at the end of every day

env:
  LOCATION: "uksouth" # Region for all Azure resources

jobs:
  deployDev:
    name: Deploy to Dev
    environment:
      name: Dev
    env:
      ENVIRONMENTNAME: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy infrastructure
      working-directory: deploy
      run: |
        az deployment sub create \
          --location '${{ env.LOCATION }}' \
          --name 'allowedLocationsPolicyDeploy-${{ env.ENVIRONMENTNAME }}' \
          --parameters main.parameters.dev.json \
          --template-file main.bicep